Odometer tester
theochem/PyCI pull request #55
Opened 2024-04-25 20:23 UTC by alnaba1

@msricher  Made a test for odometer one spin for H2 system in the minimal basis, I would expect that when we pass cost of the orbitals as energies: [0.74587179 1.10115033], if q_max is bigger than 0.75 it would select only the first determinant. If it is bigger than 1.2, it would select all determinants. However, if it is bigger than 1.2 currently then we get an index error or a segmentation fault error when we tried with the H4 system. On the other hand, if we select a value lower than 0.74, then it doesn't select any determinant as expected. Can you help to figure out what's going on?

2024-04-26 15:06 UTC, msricher commented
Actually an easier solution is just, start with a `doci_wfn`, run your odometer algorithm to fill it, and then upcast it to a `fullci_wfn`:
```python3
wfn = pyci.doci_wfn(nbasis, n_up, n_dn)
# fill `wfn`
# ...
wfn = pyci.fullci_wfn(wfn)
```

You can upcast {doci,fullci}_wfn to genci_wfn, and doci_wfn to fullci_wfn.

2024-05-26 03:45 UTC, alnaba1 commented
@msricher Is there a simple way of checking if the wfn instance is one-spin or two-spin? I've updated the Odometer algorithm to check the type of the wfn object using `isinstance()` but it doesn't seem elegant since that entails having to list out every possible type of wfn object, and I'm not sure if there would be more types of wfn objects that would be implemented later and not be accounted by the types I listed here.

```python
    if isinstance(wfn, pyci.fullci_wfn):
        two_spin = True
    elif isinstance(wfn, (pyci.doci_wfn, pyci.genci_wfn)):
        two_spin = False
    else:
        raise TypeError
    while True:
        if new[-1] < wfn.nbasis and (np.sum(cost[new]) + t * cost[new[-1]]) < qmax:
            # Accept determinant and go back to last particle
            if two_spin:
                wfn.add_occs(np.vstack((new, new)))
            else:
                wfn.add_occs(new)
```

2024-05-28 17:33 UTC, msricher commented
This is fine, there's only three classes, so you can check this way.  There won't be more added.

2024-05-28 17:57 UTC, msricher commented
You can also just use the abstract superclasses `pyci.one_spin_wfn` and `pyci.two_spin_wfn`.  `instance(dociwfn, pyci.one_spin_wfn)` should be `true` etc.

2024-05-28 17:59 UTC, msricher requested changes
This looks ok to me. If the tests run, you can merge it, although I'm not as familiar with this work being done, so I'd wait for Rik to approve it.

Can you rename the h{2,4}.fcidump files to specify the basis set? E.g. h2_sto3g.fcidump.

2024-05-29 14:08 UTC, RichRick1 requested changes
Good job! There are few things that needs to be fixed:
1. I don't think there is a need to check a way function type in the odometer_one_spin algorithm. It is used only for the one_spin wavefunction and this can be checked directly in the test function when `odometer_one_spin` or `odometer_two_spin` is called.
2. Test if the expected orbitals are selected when custom cost is provided
3. Fix the test that throws the error on GH action. There is something wrong with a missing file

2024-05-29 14:08 UTC, RichRick1 commented on pyci/utility.py
> +    if isinstance(wfn, pyci.two_spin_wfn):
I don't think we need these checks in here.
There are 2 algorithms: `odometer_one_spin` and `odometer_two_spin` that are used for one_spin and two_spin wave functions

2024-05-29 14:08 UTC, RichRick1 commented on pyci/utility.py
> +                wfn.add_occs(new)
I'm not sure about those check here too.

2024-06-07 19:27 UTC, alnaba1 commented
All finished, ready to merge.

2024-07-08 20:21 UTC, msricher commented
OK, yes this is ready to be merged. Can you just rebase it on master? Then I'll merge it.

2024-07-09 00:05 UTC, alnaba1 commented
> OK, yes this is ready to be merged. Can you just rebase it on master? Then I'll merge it.

@msricher All done.

2024-07-09 04:04 UTC, merged