Adding Neumman and Dykstra algorithims.
theochem/PyCI pull request #57
Opened 2024-05-01 19:57 UTC by AlexandreDeCamargo

2024-05-01 20:36 UTC, RichRick1 requested changes
Good job @AlexandreDeCamargo @Daniel!

2024-05-01 20:36 UTC, RichRick1 commented on pyci/rdm/algorithms.py
> +    @abstractmethod
we don't the `@abstractmethod` if all child classes will just call it as `super().__init__()`

2024-05-01 20:36 UTC, RichRick1 commented on pyci/rdm/algorithms.py
> +        self.initial_guess = initial_guess
Documentation need to be provided

2024-05-01 20:36 UTC, RichRick1 commented on pyci/rdm/algorithms.py
> +    def optimize(self):
Docstings

2024-05-01 20:36 UTC, RichRick1 commented on pyci/rdm/algorithms.py
> +    def __init__(self, initial_guess:float, constraints:list, alpha:int =1, max_iterations:int =100, eps:int =1e-6):
eps: has to be float and alpha should be float
You can safely remove type check in here, because you provide default value

2024-05-01 20:36 UTC, RichRick1 commented on pyci/rdm/algorithms.py
> +    def __init__(self, initial_guess:float, constraints:list, alpha:int =1, max_iterations:int =100, eps:int =1e-6):
initial guess in np.ndarray

2024-05-01 20:36 UTC, RichRick1 commented on pyci/rdm/algorithms.py
> +        initial_guess : float
type of initial guess

2024-05-01 20:36 UTC, RichRick1 commented on pyci/rdm/algorithms.py
> +        max_iterations : int, optional
no need to specify that it's optional, unless you really want ;)

2024-05-01 20:36 UTC, RichRick1 commented on pyci/rdm/algorithms.py
> +    def __init__(self, initial_guess, constraints, alpha, max_iterations=100, eps=1e-6):
docstrings

2024-05-01 20:36 UTC, RichRick1 commented on pyci/rdm/algorithms.py
> +                C = D - X[j]
C = D - X[j] if  algorithm == 'Dykstra' else D

2024-05-01 20:36 UTC, RichRick1 commented on pyci/rdm/algorithms.py
> +class Dykstra(metaclass=ABCMeta):
you need to inherit the abstract class that is defined above
So, it should be `Dykstra(Projector)`

2024-05-01 20:36 UTC, RichRick1 commented on pyci/rdm/algorithms.py
> +class Projection(metaclass=ABCMeta):
We don't need to inherit meta class in here, the regular ABC class should be good. Meta classes gives you ability to overload methods for different types, and I don't think it's a right strategy here.

Just do ABC https://docs.python.org/3/library/abc.html#abc.ABC

2024-05-01 20:36 UTC, RichRick1 commented on pyci/rdm/algorithms.py
> +class Neumann(metaclass=ABCMeta):
If you decide to leave Neumann as a stand alone class, you can just inherit Dykstra, and for initialization just call `super().__init__()`. You don't need to rewrite the entire init

2024-05-01 20:36 UTC, RichRick1 commented on pyci/rdm/algorithms.py
> +            for projection in enumerate(self.constraints):
remove enumerate, because it returns a container of tuples, of (number, element). You are using just element

2024-05-04 00:00 UTC, DanielCalero1 commented
Hi,

I just made two commits. In the first one I fixed the issues mentioned by @RichRick1.

On the second commit I implemented Halpern's algorithm. I follow a similar structure for the convergence of the algorithm, with a given number of iterations and tolerance.

Please tell me what you think about it @RichRick1 @AlexandreDeCamargo.

2024-05-15 19:15 UTC, RichRick1 requested changes
Great job! There are some minor changes requested:
1. Change variable name from `D` to `gamma_new` to be consistent with notations
2. Follow pep8 style by adding new lines

2024-05-15 19:15 UTC, RichRick1 commented on pyci/rdm/algorithms.py
> +        D = np.copy(self.initial_guess)
Can we change the name of D to `gamma_new` just to be consistent with notations in notes?

2024-05-22 21:29 UTC, RichRick1 approved these changes
Great job! Approved

2024-05-22 21:29 UTC, merged

2024-05-22 21:30 UTC, AlexandreDeCamargo commented
Alexandre de Camargo 
reacted to your message: 












From: Valerii Chuiko ***@***.***>
Sent: Wednesday, May 22, 2024 9:29:52 PM
To: theochem/PyCI ***@***.***>
Cc: Alexandre de Camargo ***@***.***>; Mention ***@***.***>
Subject: Re: [theochem/PyCI] Adding Neumman and Dykstra algorithims. (PR #57)
 







Caution:
External email. 







Merged 
#57 into master.
—
Reply to this email directly, 
view it on GitHub, or 
unsubscribe.
You are receiving this because you were mentioned.Message
 ID: ***@***.***>